[package]
name = "Chargen Scenarios"
description = "An alternate start / chargen overhaul mod for Morrowind."
homepage = "https://www.nexusmods.com/morrowind/mods/56341"
repository = "https://github.com/jhaakma/chargenScenarios"
authors = [ "Merlord",]
version = "1.0.2"

[dependencies]
assets = [ "MWSE\\mods\\mer\\chargenScenarios",]

[dependencies.mwse]
buildnumber = 4093

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.33.2"
url = "https://www.nexusmods.com/morrowind/mods/51009?tab=files"

[dependencies.mods."MWSE Character Creation Name Generator"]
mwse-module = "Aleist3r.Character Creation Name Generator"
url = "https://www.nexusmods.com/morrowind/mods/46189?tab=files"

[dependencies.mods."Randomised Chargen"]
mwse-module = "RandomChargen"
url = "https://www.nexusmods.com/morrowind/mods/46915?tab=files"
