[package]
name = "Chargen Scenarios"
description = "An alternate start / chargen overhaul mod for Morrowind."
repository = "https://github.com/jhaakma/chargenScenarios"
authors = [ "Merlord",]
version = "0.2.0"

[dependencies]
assets = [ "MWSE\\mods\\mer\\chargenScenarios",]

[dependencies.mwse]
buildnumber = 4093
